source 'https://github.com/CocoaPods/Specs'

platform :ios, 8.0

# Add Application pods here


target :unit_tests, :exclusive => true do
  link_with '<%= test_target_name %>'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
  pod 'OHHTTPStubs'
end


pod 'AFNetworking'
pod 'Mantle'
pod 'SDWebImage'